services:
  emby-sync:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: emby-sync:latest
    container_name: emby-sync
    environment:
      CONFIG_PATH: /app/config/emby-sync.yml
    volumes:
      - "D:\\docker\\emby-sync\\config:/app/config:ro"
      - "D:\\docker\\emby-sync\\downloads:/app/downloads"
      - "D:\\docker\\emby-sync\\state:/app/state"
    restart: "no"

    tty: false
    stdin_open: false
